CREATE TRIGGER UpdatePrice
AFTER INSERT ON BOOKING
FOR EACH ROW BEGIN
DECLARE remaining INT;
SELECT
    (SELECT NUMSEATS
     FROM FLIGHT
     WHERE FLIGHT.FLIGHTNO = NEW.FLIGHTNO
         AND FLIGHT.DAY = NEW.DAY
         AND FLIGHT.MONTH = NEW.MONTH
         AND FLIGHT.YEAR = NEW.YEAR ) -
    (SELECT COUNT(*)
     FROM BOOKING
     WHERE BOOKING.FLIGHTNO = NEW.FLIGHTNO
         AND BOOKING.DAY = NEW.DAY
         AND BOOKING.MONTH = NEW.MONTH
         AND BOOKING.YEAR = NEW.YEAR )
INTO remaining;
IF remaining < 20 THEN
    UPDATE FLIGHT
    SET PRICE = 4000
    WHERE FLIGHT.FLIGHTNO = NEW.FLIGHTNO
        AND FLIGHT.DAY = NEW.DAY
        AND FLIGHT.MONTH = NEW.MONTH
        AND FLIGHT.YEAR = NEW.YEAR;
END IF;
END;

